// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// DEBUG: Log env var status on client init
console.log('[Supabase Client Init]', {
  VITE_SUPABASE_URL_present: !!SUPABASE_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY_present: !!SUPABASE_PUBLISHABLE_KEY,
  env_mode: process.env.NODE_ENV,
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// If env vars are missing, export a lightweight mock to avoid a hard runtime crash
let _supabase: ReturnType<typeof createClient> | any;
let _isMock = false;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('[Supabase Client] Using MOCK mode because env vars missing');
  _isMock = true;
  // Minimal mock implementing the auth methods used by the app
  const noop = () => {};

  _supabase = {
    auth: {
      onAuthStateChange: (_cb: any) => ({ data: { subscription: { unsubscribe: noop } } }),
      getSession: async () => ({ data: { session: null } }),
      // match supabase-js modern API
      signInWithPassword: async (_: { email: string; password: string }) => ({
        error: { message: 'Supabase not configured in frontend env. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY' },
        data: null,
      }),
      signUp: async (_: any) => ({
        error: { message: 'Supabase not configured in frontend env. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY' },
        data: null,
      }),
      signOut: async () => ({ error: null }),
    },
    // allow table-like calls to fail gracefully if used
    from: () => ({ select: async () => ({ data: null }), insert: async () => ({ data: null }) }),
  } as unknown as ReturnType<typeof createClient>;
} else {
  console.log('[Supabase Client] Creating REAL client with provided credentials');
  _isMock = false;
  _supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

export { _isMock as isMockMode };
export const supabase = _supabase;